before_script:
  - apt-get update && apt-get install -y docker.io
  - docker version

stages:
  - build
  - test
  - dockerize
  - deploy

maven_build:
  image: maven:3-eclipse-temurin-8-focal
  stage: build
  script:
    - mvn clean package
  artifacts:
    when: on_success
    paths:
      - "target/*.jar"

maven_test:
  image: maven:3-eclipse-temurin-8-focal
  stage: test
  script:
    - mvn verify
  artifacts:
    when: on_success
    paths:
      - "target/*.jar"

docker_build:
  stage: dockerize
  script:
    - docker build -t spring-app -f src/Dockerfile .

deploy:
  stage: deploy
  script:
    - docker run -d -p 8080:8080 spring-app