version: '3.7'

networks:
  lemoncode-challenge:
volumes:
  data:

services:
  front:
    image: front:latest
    container_name: front
    ports:
      - "8080:3000"
    networks:
      - lemoncode-challenge
  back:
    container_name: topics-api
    image: topics-api:latest
    networks:
      - lemoncode-challenge
  mongodb:
    image: mongo
    container_name: some-mongo
    volumes:
      - data:/data/db

