apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-front
  labels:
    app: cm-front
data:
  NODE_ENV: "production"
  PORT: "8080"
  DB_HOST:  "service-db"
  DB_USER:  "postgres"
  DB_PASSWORD:  "postgres"
  DB_PORT:  "5432"
  DB_NAME:  "todos_db"
  DB_VERSION: "10.4"
